version: '3.9'

volumes:
  postgres_data:
#  static_volume:
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - db
#  web:
#    build: .
#    volumes:
#      - static_volume:/home/orders/static
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#      - redis
#  celery:
#    restart: always
#    build: .
#    command: celery -A orders worker -l info
#    depends_on:
#      - db
#      - redis
